### PR TITLE
zju_09 adds 6 new styles 

### PR DESCRIPTION
**Pull request by katie-chen2**
1. casual lifestyle
result of test image
image

2. chinese girl among plum blossoms
result of test image
image

3. barbie doll
result of test image
image

4. innocent girl in white dress
result of test image
image

5. elegant princess
result of test image
image

6. pixy girl
result of test image
image

### CODE REVIEW

**Comment by katie-chen2** [comment]
I also tested the above style models on a variety of other girls' faces, all yielding fairly stable results. 
The following are a few samples of the results:
1. casual lifestyle
image
2. chinese girl among plum blossoms
d1e6e9b3bcbe1f49491485ceb480964
3. barbie doll
image
4. innocent girl in white dress
image
5. elegant princess
257635a784c320958ee439bd0971fa9

7. pixy girl
image

**Review by prhloveayg — APPROVED** [review]
pretty good!

**Comment by katie-chen2** [comment]
adding test results.
3. barbie doll
942223d252a11b9906f517b3734d128
df7d381e5543f79f5c41ec93611d812
c0cf186e2c3be7dc738c177cd658dc3
image
image
image

**Review by sunbaigui — APPROVED** [review]

**Comment by katie-chen2** [comment]
resolved code conflict

**Pull request merged**
