### PR TITLE
zju_19 provides a new style of cheongsam

### PR DESCRIPTION
**Pull request by chkhu**
We offer a new style model compatible with MajicmixRealistic_v6：旗袍风(Cheongsam)

Portraits used to train the model:
image

The outcome:
image

### CODE REVIEW

**Comment by sunbaigui** [comment]
'multiplier_human': 1.15, this weight parameter is  currently highest one, could you do extra few id testing to find validate it.

**Comment by hehaha68** [comment]
I have tested this style and the results look quite good. Here are a few suggestions:

1. 'add_prompt_style' will be concatenated with 'pos_prompt_with_style', so there will be repetition in your prompt here.


2. Is 'asymmetric sleeves' in the 'neg_prompt' very important? It may affect other styles. I tried adding 'symmetrical short sleeves' in the 'pos_prompt' and found the results look good too.

3. You can try reducing the 'multiplier_human' a bit, 0.95 still looks okay to me.

**Comment by hehaha68** [comment]
nice style

**Comment by chkhu** [comment]
> 'multiplier_human': 1.15, this weight parameter is currently highest one, could you do extra few id testing to find the best weight?

We have tested several other options and 1.15 seemed unnecessary as you suggested. We went through some trial runs and altered it to be 0.95. The result still looks satisfying.

> I have tested this style and the results look quite good. Here are a few suggestions:
> 
> 1. 'add_prompt_style' will be concatenated with 'pos_prompt_with_style', so there will be repetition in your prompt here.
> 
> 
> 2. Is 'asymmetric sleeves' in the 'neg_prompt' very important? It may affect other styles. I tried adding 'symmetrical short sleeves' in the 'pos_prompt' and found the results look good too.
> 3. You can try reducing the 'multiplier_human' a bit, 0.95 still looks okay to me.

For 1, I've removed the repetition part of the pos_prompt in the latest commit.

For 2, I replaced it by adding 'beautiful chinese embroidery, symmetrical short sleeves' in the pos_prompt as you suggested. The result looks good and meanwhile avoiding affecting other models since the the neg_prompt is shared by all other LoRA models. 

For 3, 0.95 looks great.


This actually brought up a problem. Designated default neg_prompts for one single model are inevitably shared according to the current code, causing problems for other models. if default neg_prompts can be bound to a single style instead of all styles, It might be helpful for enriching styles for this project.
Aimming at this, we plan to create a new PR that fixes this problem later.

**Comment by sunbaigui** [comment]
> > 'multiplier_human': 1.15, this weight parameter is currently highest one, could you do extra few id testing to find the best weight?
> 
> We have tested several other options and 1.15 seemed unnecessary as you suggested. We went through some trial runs and altered it to be 0.95. The result still looks satisfying.
> 
> > I have tested this style and the results look quite good. Here are a few suggestions:
> > 
> > 1. 'add_prompt_style' will be concatenated with 'pos_prompt_with_style', so there will be repetition in your prompt here.
> > 
> > 
> > 
> > 2. Is 'asymmetric sleeves' in the 'neg_prompt' very important? It may affect other styles. I tried adding 'symmetrical short sleeves' in the 'pos_prompt' and found the results look good too.
> > 3. You can try reducing the 'multiplier_human' a bit, 0.95 still looks okay to me.
> 
> For 1, I've removed the repetition part of the pos_prompt in the latest commit.
> 
> For 2, I replaced it by adding 'beautiful chinese embroidery, symmetrical short sleeves' in the pos_prompt as you suggested. The result looks good and meanwhile avoiding affecting other models since the the neg_prompt is shared by all other LoRA models.
> 
> For 3, 0.95 looks great.
> 
> image
> But it actually brought up a problem. Designated default neg_prompts for one single model are inevitably shared according to the current code, causing problems for other models. if default neg_prompts can be bound to a single style instead of all styles, It might be helpful for enriching styles for this project. Aimming at this, we plan to create a new PR that fixes this problem later.

you can add an optional neg prompt in the style config, and leave the original one as global defualt value. looking forward to your next PR.

**Comment by sunbaigui** [comment]
the last suggestion: try to make the image smaller by using cv2 jpg overwrite it.
image

**Review by sunbaigui — APPROVED** [review]

**Comment by chkhu** [comment]
The preview image has been reduced to a proper size (53KB)
image

Thank you for you advices. We really appreciate that.

**Pull request merged**
