### PR TITLE
zju_01

### PR DESCRIPTION
**Pull request by BWDforce**
[comment.md](https://github.com/modelscope/facechain/files/12595201/comment.md)

### CODE REVIEW

**Comment by BWDforce** [comment]
使用要求的人像图片进行了人像 LoRA 训练

提供兼容 MajicmixRealistic_v6 的风格模型：中国风(Chinese Traditional Style)。

中国风效果展示

chinese

提供兼容 MajicmixRealistic_v6 的风格模型：科幻风(Science Fiction Style)。

科幻风效果展示

chinese

提供兼容 MajicmixRealistic_v6 的风格模型：西部风(Wild West Style)。

西部风效果展示

chinese

**Comment by sunbaigui** [comment]
please refer to https://github.com/modelscope/facechain/pull/225. try to reduce the size of preview image. 40~50K might be ok.

**Comment by hehaha68** [comment]
The 'cloth_name' field in styles can be removed. And it seems the 'img' field is missing.

For reference:
{'name': '雪山羽绒服风(Jacket in Snow Mountain)',
     'img': './style_image/Jacket_in_Snow_Mountain.jpg',
     'model_id': 'iotang/lora_testing',
     'revision': 'v7',
     'bin_file': 'puffy_jacket-1.0.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.9,
     'add_prompt_style': 'close-up, fur collar, ((jacket)), shirt, pants, winter, (bright sunny day, snow mountain, alpine slopes, snow), gyaru, fashion, trendy, gentle hair'},

Please save the style images in the style_image folder.

**Comment by BWDforce** [comment]
We have finished the required modification.

**Comment by BWDforce** [comment]
优化了中国风和科幻风的模型，修复了面部污点和不自然领口的问题
中国风修改后：
chinese
科幻风修改后：
science

**Comment by BWDforce** [comment]
我们已经完成了目前的Sync

**Pull request closed without merging**
