### PR TITLE
zju_06

### PR DESCRIPTION
**Pull request by wzhao510**
We offer a new style model compatible with MajicmixRealistic_v6：日系和服风(Kimono Style)
Portraits used to train the model:
标准id
The outcome:

### CODE REVIEW

**Comment by sunbaigui** [comment]
can you try to do more experiments to find a better weights of style to enhance the fedelity of the cloth. try to enhance this 'multiplier_style': 0.2.

**Comment by wzhao510** [comment]
Through experiments, we enhance the multiplier-style to 0.45 and add prompts '(linen:1.4)' to enhance the fidelity of the cloth
the results:

**Comment by sunbaigui** [comment]
try to compress this image 
image

**Comment by wzhao510** [comment]
We have compressed the style image.
Kimono

**Review by sunbaigui — APPROVED** [review]

**Pull request merged**
