### PR TITLE
zju_21

### PR DESCRIPTION
**Pull request by SoulNut**
提供 1 个兼容 MajicmixRealistic_v6 的风格模型：苗族服装风(miao style)。

用于训练的第一组人像：
woman_1
woman_2

测试结果：
miao_1
miao_2
miao_3
miao_4
miao_5
miao_6

用于训练的第二组人像：
girl_1
girl_2

测试结果：
miao_7
miao_8
miao_9
miao_10
miao_12
miao_13

### CODE REVIEW

**Comment by sunbaigui** [comment]
is this style duplicate with 壮族服装风(Zhuang style) ？

**Comment by SoulNut** [comment]
The Miao and Zhuang are two ethnic minorities in China. They have a unique and rich culture and traditional costumes. Miao costumes pay attention to details, rich colors, and gorgeous decoration, while Zhuang costumes tend to be simple and practical, relatively conservative colors. The two styles of dress have their own characteristics and are not duplicated.

**Comment by SoulNut** [comment]
> is this style duplicate with 壮族服装风(Zhuang style) ？

They are two different styles of minority clothing

**Comment by hehaha68** [comment]
Hello, I tested this style and found that the generated images often have issues with tangled headwear and necklaces, bad hands. This may require tuning the prompt and parameters. Also, the 'cloth_name' field in styles can be removed.

**Pull request closed without merging**
