### PR TITLE
ZJU_19 [ADD] a new style of Min'guo Student(民国学生风)

### PR DESCRIPTION
**Pull request by chkhu**
Based on the LoRA model **trained by ourselves** using images collected from the Internet, we offer a new style of Min'guo student style(民国学生风). The result appears stunning. 👇Check out

- Portraits used to train the model.
image

- Result
minguo_pack

### CODE REVIEW

**Comment by sunbaigui** [comment]
from the results above, there's little artifact of the pic. please do more experiments to find the best weighting of human & style.

**Comment by chkhu** [comment]
After 6 trial runs and comparison, I consider 0.5:0.9 to be a ‘local optimum’ weight match. Its results are close to the original 0.5:0.95, but a bit more stable
image

- Test record:
image


- Trial runs:
image

**Comment by sunbaigui** [comment]
there is still some artifact, maybe you should tune prompt as well.

**Comment by sunbaigui** [comment]
please refer to #230 . They tuned the specific pos prompt related to the syle lora, and then get a more fantastic and robust result.

**Comment by chkhu** [comment]
> there is still some artifact, maybe you should tune prompt as well.

Thank you so much for your suggestion, but can you be more specific on what the artifacts are? My teammates and I are having a hard time spoting the exact the artifacts you were refering to. That would help us a lot to tune the prompts more precisely. Thanks again.

**Pull request closed without merging**
