### PR TITLE
(zju_15) 提供 1 个新的风格模型

### PR DESCRIPTION
**Pull request by iotang**
提供 1 个兼容 MajicmixRealistic_v6 的风格模型：雪山羽绒服风(Jacket in Snow Mountain)。

- 用于训练的人像

用于训练的人像

- Jacket in Snow Mountain

Jacket in Snow Mountain

### CODE REVIEW

**Comment by hehaha68** [comment]
I tested this style, the effect is pretty good. Can we continue to tune the prompt and parameters a bit, the multiplier_style can be lower.

My prompt and parameters:
'multiplier_style': 0.6,
'multiplier_human': 0.9,
'add_prompt_style': '1 girl, close-up, fur, ((jacket)), shirt, pants, winter, (bright sunny day, snow mountain, alpine slopes, snow), gyaru, fashion, trendy, gentle hair'

**Comment by iotang** [comment]
> I tested this style, the effect is pretty good. Can we continue to tune the prompt and parameters a bit, the multiplier_style can be lower.
> 
> My prompt and parameters: 'multiplier_style': 0.6, 'multiplier_human': 0.9, 'add_prompt_style': '1 girl, close-up, fur, ((jacket)), shirt, pants, winter, (bright sunny day, snow mountain, alpine slopes, snow), gyaru, fashion, trendy, gentle hair'  

Wow, your tune results works obviously better. Let us update those prompts and parameters after merge.

**Comment by sunbaigui** [comment]
> > I tested this style, the effect is pretty good. Can we continue to tune the prompt and parameters a bit, the multiplier_style can be lower.
> > My prompt and parameters: 'multiplier_style': 0.6, 'multiplier_human': 0.9, 'add_prompt_style': '1 girl, close-up, fur, ((jacket)), shirt, pants, winter, (bright sunny day, snow mountain, alpine slopes, snow), gyaru, fashion, trendy, gentle hair'  
> 
> Wow, your tune results works obviously better. Let us update those prompts and parameters after merge.

hi, @iotang if there's a better parameter & prompt, chould you change it first, and update your style showcase.

**Comment by iotang** [comment]
> 

I updated parameter and prompts and the result is as shown below. Human LoRA may make the results different.
Style image has been updated too.
new result

**Pull request merged**
